### ISSUE TITLE
Tracking Current outstanding pre-commit repo review actions

### ISSUE THREAD

**Issue by HGWright** [SciTools/python-stratify#277]
## 📰 Custom Issue

#276 will add a pre-commit action checking our repo against repo review.

To add this I have set all of the tests that currently fail to ignore in the pyproject.toml. We need to consider which/how many of these we can/want to implement into stratify, and which we are happy to leave on ignore.

```[tasklist]
### Tasks
- [ ] PY004: Has docs folder
- [ ] PP302: Sets a minimum pytest to at least 6
- [ ] PP304: Sets the log level in pytest
- [ ] PP305: Specifies xfail_strict
- [ ] PP306: Specifies strict config
- [ ] PP307: Specifies strict markers
- [ ] PP309: Filter warnings specified
- [ ] PY007: Supports an easy task runner (nox or tox)
- [ ] PP003: Does not list wheel as a build-dep
- [ ] PC111: Uses blacken-docs
- [ ] PC140: Uses a type checker
- [ ] PC160: Uses a spell checker
- [ ] PC170: Uses PyGrep hooks (only needed if rST present)
- [ ] PC180: Uses a markdown formatter
- [ ] PC190: Uses Ruff
- [ ] MY100: Uses MyPy (pyproject config)
- [ ] RF001: Has Ruff config
- [ ] RTD100: Uses ReadTheDocs (pyproject config)
```
